### ISSUE TITLE
Line continuation in if statements not supported

### ISSUE THREAD

**Issue by Garados007** [fujidana/vscode-igorpro#28] opened 2024-09-03 15:20 UTC
In Igor you can use line continuation to split up long lines into multiple ones and they are still considered as one command: `DisplayHelpTopic "Line Continuation"`.

```igorpro
Function test()
	variable condition1 = 1, condition2 = 2
	if(condition1 \
		|| condition2)
		print "Hello"
	endif // error: Expected "End" but "endif" found.
End
```

**Comment by Garados007** [comment] 2024-09-03 15:27
After looking a bit at our code base, I found out that line continuation in general is not supported by your extension. You can safely assume that line continuation can be used anywhere in user code. In reality they are some tricky edge cases for which this isn't allowed, but those are difficult to specify and find.

**Comment by fujidana** [comment] 2024-09-04 03:02
While I wrote somewhere that line continuation is not supported, it doesn't mean it is impossible or difficult to support it. In my experience I rarely got into situations where line continuation is necessary, and so just I put the priority of supporting it low.

Current diagnostics (problem matching) is implemented in [main/src/grammar.pegjs](../blob/main/src/grammar.pegjs)), written in PEGGY (PEG.js) syntax. In this file a series of continuous whitespaces and horizontal tabs is defined as below.

```PEG.js
_0 = [ \t]* { return text(); } // 0 or more
_1 = [ \t]+ { return text(); } // 1 or more
```

Replacing them with the code below, every line continuation will be treated as an equivalent of a white space.

```PEG.js
_0 = ([ \t] / '\\' ('\n' / '\r' / '\r\n'))* { return text(); } // 0 or more
_1 = ([ \t] / '\\' ('\n' / '\r' / '\r\n'))+ { return text(); } // 1 or more
```

Practically it is not an expected behavior and better approach will be that defining the new pattern matchers with new names such as `_0LC` and `_1LC`, for example,  and replacing `_0` and `_1` with the ones with `LC` postfix where line continuation is allowed. The problem is where it is allowed and where it isn't. For a while I won't have spare time to check them. Can you afford do make a pull request? If you are new to developing a VS code extension, I can help a bit to set up the environment.

**Comment by Garados007** [comment] 2024-09-04 14:34
> The problem is where it is allowed and where it isn't.

I don't think its worth the time to find out all those places where a line continuation in Igor 9 is allowed and where not. It is very likely that some will be missing and others will be wrong and the rules have to be touched again. I think its okay to allow line continuation at all places and let Igor itself decide if its allowed or not.

Also it is very likely that a future Igor version might allow line continuation at more places - if not all places. When this happens, all the effort you put into finding the right places is wasted, and you have to update the grammar again.

> Can you afford to modify code and make a pull request? If you are new to developing a VS code extension, I can help a bit to set up the environment.

I have already tried to set up the environment locally, but stopped because there is a large undocumented list of additional tools and VS code extensions that are required. And the next day you already published a fix for my issue, so I didn't continue.

It could be very helpful if you write a list of all required tools (and maybe how to setup if its non trivial) in the README or wiki. This would allow me (and others) to fix one or two bugs if I have some spare time left.

**Comment by fujidana** [comment] 2024-09-05 07:22
> I think its okay to allow line continuation at all places and let Igor itself decide if its allowed or not.

OK. Then it is not difficult. I will do it within a day.
And I now understood that just a simple and lenient rule will be in most cases enough.

> I have already tried to set up the environment locally, but stopped because there is a large undocumented list of 

Sorry for lacking documents. I just wrote an installation guide for developers in [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md). While this time I am going to make a fix for line continuation, with this doc I hope you (and others) can try the extension with some customization or modification.

**Comment by fujidana** [comment] 2024-09-06 09:16
I found the examples I showed above are incorrect.

> _0 = ([ \t] / '\\' ('\n' / '\r' / '\r\n'))* { return text(); }

Since Peggy does not do back-tracking (unlike regular expression), this rule captures CR (`\r`) only for lines ending with CR+LF (`\r\n`). To work correctly with windows-style text, it must be like:

> _0 = ([ \t] / '\\' ('\n' / '\r\n' / '\r'))* { return text(); }
> // or
> _0 = ([ \t] / '\\' ('\n' / '\r' '\n'?))* { return text(); }

**Comment by fujidana** [comment] 2024-09-06 09:49
Modified code has been committed and the updated version has been sent into the market place.
629e747b9b985d25e685ab18daba5942432cf101

**Closed by fujidana** 2024-09-06 09:49 UTC
Labels: enhancement
